version: '3.3'
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:4085 --timeout 28800 InterfaceDjango.wsgi:application
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "4085:4085"
    environment:
      - DJANGO_SETTINGS_MODULE
      - DB_HOST
    depends_on:
      - db

  celery:
    build: .
    command: celery -A InterfaceDjango.configcelery worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://db:6379/0
    depends_on:
      - db

  db:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  static_volume: {}
  media_volume: {}
