# Generated by Django 4.1.5 on 2023-04-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confdt',
            options={'verbose_name': 'Configuración Rango de Fecha', 'verbose_name_plural': 'Configuración Rangos de Fechas'},
        ),
        migrations.AlterModelOptions(
            name='confempresas',
            options={'verbose_name': 'Configuración Empresa', 'verbose_name_plural': 'Configuración Empresas'},
        ),
        migrations.AlterModelOptions(
            name='confserver',
            options={'verbose_name': 'Configuración Servidor', 'verbose_name_plural': 'Configuración Servidores'},
        ),
        migrations.AlterModelOptions(
            name='confsql',
            options={'verbose_name': 'Configuración Proceso Sql', 'verbose_name_plural': 'Configuración Procesos Sql'},
        ),
        migrations.AlterModelOptions(
            name='conftipo',
            options={'verbose_name': 'Configuración Tipo Servidor', 'verbose_name_plural': 'Configuración Tipos de Servidores'},
        ),
        migrations.AlterModelOptions(
            name='permisosbarra',
            options={'managed': False, 'permissions': (('nav_bar', 'Ver la barra de menú'), ('cubo', 'Generar cubo de ventas'), ('interface', 'Generar interface contable'), ('plano', 'Generar archivo plano'), ('informe_bi', 'Informe Bi'), ('actualizar_base', 'Actualzación de datos'), ('actualizacion_bi', 'Actualizar Bi'), ('admin', 'Ir al Administrador'))},
        ),
        migrations.AlterField(
            model_name='confdt',
            name='nbDt',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='nmDt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Rango de Fecha'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='txDtFin',
            field=models.TextField(blank=True, null=True, verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='txDtIni',
            field=models.TextField(blank=True, null=True, verbose_name='Fecha Inicial'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='dataset_id_powerbi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dataset PowerBi'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='dbBi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Base de datos Bi'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='dbSidis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Base de datos Sidis'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='estado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Base'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nbServerBi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Id Servidor PowerBi'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nbServerSidis',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Id Servidor Sidis'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureCsv',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Csv'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureCsv2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Csv2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureExcel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Excel'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureExcel2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Excel2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureInterface',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento Interface'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureSql',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Sql'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='report_id_powerbi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id Reporte PowerBi'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureCargue',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql del Cargue'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureCsv',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql a Csv'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureCsv2',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql a Csv2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureExcel',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql a Excel'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureExcel2',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql a Excel2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureExtrae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesos sql Extractor'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureInterface',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql de Interface'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureSql',
            field=models.TextField(blank=True, null=True, verbose_name='Procesos sql a Sql'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='url_powerbi',
            field=models.TextField(blank=True, null=True, verbose_name='Url Pública PowerBi'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='hostServer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='nbServer',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id del Servidor'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='nbTipo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='nmServer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripción del Servidor'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='portServer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Puerto'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nbSql',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id del Proceso'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nmProcedure_out',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Procedimiento Extractor'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nmReporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Proceso'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='txDescripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del Proceso'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='txSql',
            field=models.TextField(blank=True, null=True, verbose_name='Sql Script'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='txTabla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla de Inserción'),
        ),
        migrations.AlterField(
            model_name='conftipo',
            name='nbTipo',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='conftipo',
            name='nmUsr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='conftipo',
            name='txPass',
            field=models.TextField(blank=True, null=True, verbose_name='password'),
        ),
    ]
