# Generated by Django 4.1.5 on 2023-04-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroauditoria',
            options={'verbose_name': 'Registro de Auditoria', 'verbose_name_plural': 'Registro de Auditorias'},
        ),
    ]
