# Generated by Django 4.1.5 on 2023-03-12 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_database_permissiondb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiondb',
            name='user',
        ),
        migrations.AddField(
            model_name='permissiondb',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
