# Generated by Django 4.1.5 on 2023-03-12 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_permissiondb_user_permissiondb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PermissionDb',
        ),
    ]
